/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Español
 */
public class Conversiones extends javax.swing.JFrame {

    int numero1=0;
    int numero2=0;
    int numero3=0;
    int numero4=0;
    int numero5=0;
    int numero6=0;
    int suma=0;
    int resta=0;
    int multiplicacion=0;
    int opcion;
    public Conversiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btnaceptar = new javax.swing.JButton();
        Txtnumero2 = new javax.swing.JTextField();
        Txtnumero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btnaceptar1 = new javax.swing.JButton();
        Btnaceptar2 = new javax.swing.JButton();
        Btnaceptar3 = new javax.swing.JButton();
        Btnigual = new javax.swing.JButton();
        Btnaceptar5 = new javax.swing.JButton();
        Labelresultado = new javax.swing.JLabel();
        Labelsimbolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btnaceptar.setText("+");
        Btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");

        Btnaceptar1.setText("-");
        Btnaceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnaceptar1ActionPerformed(evt);
            }
        });

        Btnaceptar2.setText("X");
        Btnaceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnaceptar2ActionPerformed(evt);
            }
        });

        Btnaceptar3.setText("C");
        Btnaceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnaceptar3ActionPerformed(evt);
            }
        });

        Btnigual.setText("=");
        Btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnigualActionPerformed(evt);
            }
        });

        Btnaceptar5.setText("/");
        Btnaceptar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnaceptar5ActionPerformed(evt);
            }
        });

        Labelresultado.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 102, 255)));

        Labelsimbolo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Labelsimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Labelresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Btnaceptar2)
                                .addComponent(Btnaceptar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Btnaceptar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Btnaceptar3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Btnaceptar5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Btnigual)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Txtnumero1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Txtnumero2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Labelsimbolo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnaceptar1)
                    .addComponent(Btnaceptar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnaceptar2)
                    .addComponent(Btnaceptar5)
                    .addComponent(Btnigual))
                .addGap(18, 18, 18)
                .addComponent(Labelresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaceptarActionPerformed
        // TODO add your handling code here:
        opcion=1;
        Labelsimbolo.setText("+");
    }//GEN-LAST:event_BtnaceptarActionPerformed

    private void Btnaceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnaceptar1ActionPerformed
        // TODO add your handling code here:
        opcion=2;
        Labelsimbolo.setText("-");
    }//GEN-LAST:event_Btnaceptar1ActionPerformed

    private void Btnaceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnaceptar2ActionPerformed
        // TODO add your handling code here:
        opcion=3;
        Labelsimbolo.setText("X");
    }//GEN-LAST:event_Btnaceptar2ActionPerformed

    private void Btnaceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnaceptar3ActionPerformed
        // TODO add your handling code here:
        Txtnumero1.setText("");
        Txtnumero2.setText("");
        Labelresultado.setText("");
    }//GEN-LAST:event_Btnaceptar3ActionPerformed

    private void BtnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnigualActionPerformed
        // TODO add your handling code here:
        switch(opcion){
            case 1 :
                numero1=Integer.parseInt(this.Txtnumero1.getText());
                 numero2=Integer.parseInt(this.Txtnumero2.getText());
                suma=numero1+numero2;
                Labelresultado.setText(String.valueOf(suma));
                break;
            case 2 :  
                numero3=Integer.parseInt(this.Txtnumero1.getText());
                 numero4=Integer.parseInt(this.Txtnumero2.getText());
                resta=numero3-numero4;
                Labelresultado.setText(String.valueOf(resta));
                break;
            case 3 :
                numero5=Integer.parseInt(this.Txtnumero1.getText());
                numero6=Integer.parseInt(this.Txtnumero2.getText());
                multiplicacion=numero5*numero6;
                Labelresultado.setText(String.valueOf(multiplicacion));
                break;
                
                
        }
    }//GEN-LAST:event_BtnigualActionPerformed

    private void Btnaceptar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnaceptar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btnaceptar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnaceptar;
    private javax.swing.JButton Btnaceptar1;
    private javax.swing.JButton Btnaceptar2;
    private javax.swing.JButton Btnaceptar3;
    private javax.swing.JButton Btnaceptar5;
    private javax.swing.JButton Btnigual;
    private javax.swing.JLabel Labelresultado;
    private javax.swing.JLabel Labelsimbolo;
    private javax.swing.JTextField Txtnumero1;
    private javax.swing.JTextField Txtnumero2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
